html/script.js
Now handles `&lat`, `&lon`, and `&zoom` query parameters.
Additionally, if you specify an `&icao` query param without a `&zoom`, I changed the default zoom to be 9 instead of 8.
If `icao` is specified, it takes priority over `&lat` and `&lon`.
=> Handle lat, lon, and zoom url parameters.

html/layers.js
A chart can be seen here showing the browsers that support arrow functions: https://caniuse.com/#feat=es6
=> Fix support for older browsers (Most notability pre iOS 10).

html/layers.js
The correct subdomains for CARTO Basemaps are `a-d` and although, currently, `e-z` subdomains work they are going to be removed soon.
=> Update CARTO Basemaps url to use correct subdomains

html/script.js
Check if the field already has the text that we are about to write to it.  This decreases dom updates slightly improving performance and makes it easier to copy text for the selected aircraft.
This does not decrease the number of updates around the table but it makes it a lot easier to copy the callsign, registration number, ICAO, etc since the element is only changed when it updates rather then on every refresh.
=> decrease dom updates to selected aircraft

html/formatter.js
use em quad instead of non breaking space for verticalRateTriangle when there is no change.  This aligns the numbers for the altitude on both windows and mac regardless of ascending, descending or level.
=> use em quad for verticalRateTriangle

README.md, html/config.js, html/defaults.js, html/script.js
* support local share links
* use URLSearchParams for parameters so we don't need to worry about injection.
=> Support share links on local installs and switch the parameter building to URLSearchParams 

README-query.md, html/early.js, html/script.js
This will add a setting (disabled by default) to persist the filters to local storage.  
This should resolve #14
I tested with all tracks enabled and then enabled a filter and it cleared all non selected plans that don't match.
=> Add a setting to persist filters to local storage.

zstddec/notes.md
init() doesn't throw an error if it fails, instead, it rejects a promise. you can catch that by using .catch OR you can wrap this in an async iife and with `try { await init(); } catch(e) { webAssemblyFail(e) }`. try catch will only catch the rejection if the promise is awaited in the try block
=> Fix zstddec example try/catch

html/script.js
Prior calculation of the top-left corner location of the infoBox could result in negative values, placing the element (partially) out of view. Also, positioning was inconsistent, depending on whether left/right or above/below the plane marker.
With this change, the size of the infoBox is taken info account when calculating the relative position, and it ensured that the values would not be less than zero.
=> improve infoBox positioning

html/index.html
I noticed that a title shown after toggling the 'V' button changes the title from plural to singular.
I chose to just change the initial title to be singular as the long form might be described as *count of aircraft with at least one position*.
=> Inconsistent title text for span `with_positions` 'With Position:' / 'With Positions:'

install.sh
**Notes**
I noted recently that a fresh install to a rasperry pi / raspbian OS did not install `jq`.
- Without `jq` installed, several scripts which parse/modify json files fail to be created/updated, and `tar1090` functionality which rely on these json files fails to load/run correctly (e.g., `pTracks`)
- Failures, and error messages about `jq` being unavailable, can be observed via `journalctl`
- Manually installing `jq` resolved the errors
`jq` not being installed as part of the normal install process appears to be due to an omitted trailing slash when specifying the string to pass into `read` (the trailing token is required to denote the end of the last item).
This pull request inserts that trailing slash.
For reference/convenience, these are the relevant lines within `install.sh`. …
=> Bugfix - add trailing slash to install script, enabling `jq` to be installed where it is not already present

html/planeObject.js, html/script.js
Working with this for a couple of weeks we noticed two issues:
- the batches became to big, especially when users zoomed out at an aggregator site and suddenly thousands of routes were requested
- the user experience wasn't great with the five and then ten second waits
This patch series limits each individual route API call to a maximum of 100 callsigns and in return allows those calls once every second. This reduces the burst load on the route API server and improves the user experience.
The code has been tested on a production server :)
Thanks to Katia for the idea and the testing.
=> Route burst limit

html/planeObject.js, html/script.js
As requested by the API server maintainer, this will keep unresolved callsigns queued until the previous API request has been completed.
=> only have one route check API call in flight

html/config.js, html/defaults.js, html/index.html, html/script.js
This allows an obvious way from the map display to go back to a web UI that can configure a feeder setup.
Off by default.
=> add configurable link back to a config page

html/config.js, html/defaults.js, html/script.js
My personal preference is for wider, translucent, lines terrain limit/range lines. Opacity is currently not configurable.
This pull request enables the required opacity argument to be provided via configuration (I am currently patching the files after install).
Note that the supplied default value of `1.0` is completely opaque (`0.0` being completely transparent), meaning that users who do not wish to alter the opacity value will not be affected by this change.
=> Add configuration for terrain limit line opacity

html/planeObject.js
Instead of creating a wildcard access control allow origin, limit it to the route api server.
Change requested by Ramon (@kx1t)
=> improve CORS security

html/layers.js
This comments out the chartbundle layer code, as chartbundle.com is gone and adsbexchange is no longer providing those tiles. I left the code in there in case an alternate source can be located in the future.
Also adds a new layer, Special Use Airspace, from the FAA via arcgis.
=> disable chartbundle layers; add special use airspace layer

html/script.js
This is a special case for a tar1090 instance that shows the combined output of multiple readsb instances (like in a stage2 instance of the adsb.im feeder image).
This tries once to download a multiOutline.json file and remembers if it exists or if it should use the outline.json file instead. In the update loop it simply checks for a third format where points is an array of arrays. And then loops over that outer array - which in the case of the regular output.json is simply an array with just one entry.
The additional overhead is negligible, the additional feature is really cool (once you have the code to create merged outlines).
something like this can be used to create such a file:
```
from shapely.geometry import LinearRing, Polygon
from shapely.ops import unary_union
import json …
```
=> allow multi range outlines to be used

html/layers.js
Adds support for FAA VFR Sectional, VFR Terminal, IFR Low, and IFR High charts from official FAA chart server. This restores most of the charts previously provided through chartbundle.
=> Update layers.js to add support for FAA charts 

html/config.js, html/defaults.js, html/layers.js
This adds support for Mapbox vector layers by splitting the current `ol-custom024.js` file into separate JS files, adding the `olms.js` package which adds support for using Mapbox styles when an API key is provided. Additionally, I've added 4 map styles (default and bright are using v10 instead of the latest v12 because the rendering isn't correct.).
=> Add support for Mapbox vector layers

html/script.js
Aids to Navigation & Land-Based Stations show as shiptype 0 and translates to type RESE. this uses mssi_type to identify those non-ships and gives them types ANAV, LAND & COAS for identification and future filtering.
Change type for shiptype 29 to ASAR to identify it's an airborne AIS object.
=> Identify Non-Ship AIS Objects

html/layers.js
by using the customTiles URL parameter, I see no reason to artificially limit the maximum zoom
=> Allow maximum zoom of 20 on custom tiles

html/script.js
This is analog to what we do for the configLink - simply support the magic token HOSTNAME to represent the request host.
That way a reverse proxy on the system running tar1090 can allow access to geojson and icons.png regardless of where the ais_cather is running, massively simplifying configuration.
=> allow host-relative link for aiscatcher_server

html/script.js
The document.execCommand function is deprecated and the copyShareLink function does not work in Chrome (and possibly other browsers).
This PR changes the copyShareLink function to use the navigator.clipboard API instead and works in modern browsers.
=> Fix copyShareLink not working in Chrome (and possibly other browsers)
